# Generated by Django 3.0.6 on 2021-06-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='default-img.jpg', null=True, upload_to='media'),
        ),
    ]
