# Generated by Django 3.0.6 on 2021-06-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review_app', '0002_auto_20210610_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='default-img.jpg', null=True, upload_to='profile_pic'),
        ),
    ]
