# Generated by Django 3.2.4 on 2021-06-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review_app', '0003_auto_20210610_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
