# Generated by Django 3.2.4 on 2021-06-12 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_review_app', '0004_auto_20210611_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(default=1, max_length=5, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='user_rating',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_rating',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='movie_ratings', to='movie_review_app.rating'),
            preserve_default=False,
        ),
    ]
